[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base="light"
primaryColor="#ffb6c1"           # Hồng đào nhạt cho button, highlight
backgroundColor="#ffeef0"        # Nền app hồng đào rất nhạt
secondaryBackgroundColor="#ffdce0" # Sidebar hồng nhạt hơn một chút
textColor="#222222"   
